<% if(title){ %>== <%= title;%> 
=== Changing of the <%= fileName; %> file
<%if(text){%><%- text; %> <%}%> 
<%}else if(title === undefined){%>=== Changing of the <%= fileName; %> file
<%if(text){%><%- text; %> <%}%>
<%}else if(title === null){ %>== Changing of the <%= fileName; %> file
<%if(text){%><%- text; %><%}%> <%}%>


==== Prerequisites
* VS Code Editor (can be installed in your devonfw environment).

==== Changing of <%= fileName; %> in the VS Code Editor

To change the file <%= fileName; %>, you have to open it in VS Code first. 
Open VS Code and choose in the *File* context menu in the top left corner right next to the VS Code symbol *Open File...* or just use the keyboard shortcut ctrl+o. 
Based on your operating system a window with the file explorer opens. You have to navigate to <%= fileName; %> and select it. Choose the right folder manually by selecting the folders from the path `<%= filePath; %>` and select the file `<%= fileName; %>`. 
You can confirm this with the *Open* button in the bottom right corner and <%= fileName; %> will be opened in a new VS Code editor window.

Copy the following text.
[source, <%= fileType; %>]
----
<%- content; %>
----

<% if(lineNumber) { %>Insert the content into the line *<%= lineNumber%>* in the opened <%= fileName; %>.
<%}else if(placeholder) {%>To replace the content with a specific placeholder you have to locate the placeholder in the file. The fastest way is to search through the opened file and replace *<%= placeholder; %>* with the new content.
<% }else{ %>Now insert the copied text into the opened <%= fileName; %>. <% } %>
The final step is to save the file by selecting *Save* in the file context menu or by using the keyboard shortcut ctrl+s and <%= fileName; %> has been changed.

<%if(textAfter){%><%- textAfter; %><%}%>

