<% if(title){ %>== <%= title;%> 
=== Create the <%= fileName; %> file
<%if(text){%><%- text; %> <%}%> 
<%}else if(title === undefined){%>=== Create the <%= fileName; %> file
<%if(text){%><%- text; %> <%}%>
<%}else if(title === null){ %>== Create the <%= fileName; %> file
<%if(text){%><%- text; %><%}%> <%}%>

==== Prerequisites
* Existing folder you want to create the file. (If the folder doesn't exist you can create it from with the editor).
* VS Code Editor (can be installed in your devonfw environment).

==== Creating <%= fileName; %> in the VS Code Editor

Create <%= fileName; %> in the VS Code editor<% if(content) { %> and insert the following data into it. <% }%>

Opening a new file can be done by going to the file context menu in the top left corner right next to the VS Code symbol and selecting *New File* or use the keyboard shortcut ctrl+n. A new VS Code editor window will be opened with an untitled-1 filename.
<% if(content) { %> 
Copy the following text.
[source, <%= fileType; %>]
----
<%- content; %>
---- 
Now insert the copied text into the new file.
<% } %>
The next step is to save the file by selecting *Save* or *Save as* in the file context menu or by using the keyboard shortcut ctrl+s.
A file explorer window opens.
You should check if you are currently in the right directory where you want to save *<%= filePath; %>/<%= fileName;%>*. 
Select the directory `<%= filePath; %>`. If the directory does not exist, create the missing folders or run through the previous steps from the wiki again.
To save the file specify the name of the file. Paste `<%= fileName; %>` in the text field *File name:*. 
The last step is to save the file with the *Save* button in the bottom right corner and <%= fileName; %> has been created<% if(content) { %> and filled with some content%><%} %>.

<%if(textAfter){%><%- textAfter; %><%}%>

