== Create the file <%= fileName; %>

=== Prerequisites
* Existing folder you want to create the file. (If the folder doesn't exist you can create it from with the editor.)

=== Creating <%= fileName; %> in the Eclipse IDE

Create <%= fileName; %> in the Eclipse IDE<% if(content) { %> and insert the following data into it<% } %>.

First, you have to load the project directory into Eclipse by going into the *File* context menu again and selecting *Open Projects from File System...*. Eclipse opens a *Import Projects from File System or Archive* window, where you should specify your directory by selecting the *Directory...* button and choosing `<%= filePath;%>` in the Windows file explorer window and confirm the choice with the *Finish* button.
Opening a new file can be done by going to the *File* context menu in the top left corner and select *New* or use the keyboard shortcut alt+shift+n and a dropdown menu will be opened where you have to select *File*.
Eclipse opens a *Create New File* window. Select the parent folder you want to save the file into. Insert `<%= parentFolder; %>` at the top text field named *enter or select the parent folder*. If the directory does not exist, create the missing folders or run through the previous steps from the wiki again. 
Also, a name for the file is needed, so you can insert `<%= fileName; %>` in the text field *File name* or type it yourself. 
Confirm your inputs with the *Finish* button in the bottom right corner and an empty <%= fileName; %> has been created and can be edited.<% if(content) { %>
Select the following text and copy it with a right-click and the copy function or the keyboard shortcut crtl+c.
[source, <%= fileType; %>]
----
<%= content; %>
----
Now insert the copied text with the keyboard shortcut ctrl+v or with a right-click in the Eclipse editor window of the new file and the paste function or the keyboard shortcut ctrl+v. <% } %>
The final step is to save the file by selecting *Save* in the file context menu or by using the keyboard shortcut ctrl+s and <%= fileName; %> has been created <% if(content){%>with the data from above<% }%>.
