<% if(title){ %>== <%= title;%> 
=== Create a new devon4j project in the Eclipse IDE
<%if(text){%><%- text; %> <%}%> 
<%}else if(title === undefined){%>=== Create a new devon4j project in the Eclipse IDE
<%if(text){%><%- text; %> <%}%>
<%}else if(title === null){ %>== Create a new devon4j project in the Eclipse IDE
<%if(text){%><%- text; %><%}%> <%}%>


==== Prerequisites

In order to create a new application you must use the archetype provided by devon4j which uses the https://maven.apache.org/guides/introduction/introduction-to-archetypes.html[maven archetype functionality].

To create a new application, you should have installed devonfw-ide. Follow the https://devonfw.com/website/pages/docs/devonfw-ide-introduction.asciidoc.html[devonfw-ide] documentation to install the same.

==== Create the project

Firstly, create a new maven project.
Then, choose the 'devon4j-template-server' archetype.
Fill the _Group Id_, _Artifact Id_, _version_ and _package_ for your project. The _package_ name should be <%= name; %>. If you want to add an EAR generation mechanism to your project, you should fill the property _earProjectName_ with the value _Artifact Id_ + "-ear". For example, "sampleapp-ear".

==== What is generated?

The application template (archetype) generates a maven multi-module project. It has the following modules:

- *api*: module with the API (REST service interfaces, transfer-objects, datatypes, etc.) to be imported by other apps as a maven dependency in order to invoke and consume the offered (micro)services.

- *core*: maven module containing the core of the application.

- *batch*: optional module for batch(es)

- *server*: module that bundles the entire app (core with optional batch) as a WAR file.

- *ear*: optional maven module is responsible to packaging the application as a EAR file.

The toplevel pom.xml of the generated project has the following features:

- Properties definition: Spring-boot version, Java version, etc.

- Modules definition for the modules (described above)

- Dependency management: define versions for dependencies of the technology stack that are recommended and work together in a compatible way.

- Maven plugins with desired versions and configuration

- Profiles for https://devonfw.com/website/pages/docs/devon4j.asciidoc_guides.html#guide-testing.asciidoc[test stages]

<%if(textAfter){%><%- textAfter; %><%}%>

