== Changing of the <%= fileName; %> File

=== Prerequisites
* Any editor that can edit files

=== Changing of <%= fileName; %> in a Editor


To change the file <%= fileName; %>, you have to open it in the editor. 
Open the editor and choose in the file context menu in the top left corner *Open ...* mostly also keyboard shortcut ctrl+o works. 
Based on your operating system a window with the file explorer opens. You have to navigate to <%= fileName; %> and select it.  Select the right folder manually by selecting the folders from the path `<%= filePath; %>` and select the file `<%= fileName; %>`. 
You confirm this with the *Open* button in the bottom right corner <%= fileName; %> will be opened in a new editor window.

Select the following text and copy it with a right-click and the copy function or the keyboard shortcut crtl+c.
[source, <%= fileType; %>]
----
<%= content; %>
----


<% if(lineNumber) { %>Inserting the content into a specific line number can be done by a left mouse click into the line *<%= lineNumber%>* and using the keyboard shortcut ctrl+v. Not every editor provides line numbers, if they are missing you have to count the numbers yourself.
<%}else if(placeholder) {%>To replace the content with a specific Placeholder you have to locate the placeholder in the file. The fastest way is to search through the file with ctrl+f and pasting the placeholder `<%= placeholder; %>` into the *Find next* or *Find* text field that will be opened. The placeholder will be marked in the text and you can replace him with the new content.
<% }else{ %>Now insert the copied text with the keyboard shortcut ctrl+v or with a right-click in the editor window of the new file and the paste function or the keyboard shortcut ctrl+v. <% } %>
The final step is to save the file by selecting *Save* in the file context menu or by using the keyboard shortcut ctrl+s and <%= fileName; %> has been changed.