== Changing of the <%= fileName; %> File

=== Changing of <%= fileName; %> in a Editor

<% if(contentPath) {%> 
First, you want to open the file <%= contentFile; %> where you get the content from, you want to put into the new file.
Go to the file context menu in the top left corner right nand choose *Open ...*, mostly also keyboard shortcut ctrl+o works. 
Based on your operating system a window with the file explorer opens. You have to navigate to your file and select it.  This can be done by, inserting the path `<%= contentPath; %>` into the path bar, so you can jump into the right folder and select the file `<%= contentFile; %>`. 
You confirm this with the *Open* button in the bottom right corner.
The file will be opened in a new editor window where you can select the whole text with the keyboard shortcut ctrl+a or just select the text you want to copy and copy the text with ctrl+c.<% } %>

To change a File you have to open it in the editor. 
Open the editor and choose in the file context menu in the top left corner *Open ...* mostly also keyboard shortcut ctrl+o works. 
Based on your operating system a window with the file explorer opens. You have to navigate to your file and select it. This can be done by, inserting the path `<%= filePath; %>` into the path bar, so you can jump into the right folder and select the file `<%= fileName; %>`. 
You confirm this with the *Open* button in the bottom right corner.
The file will be opened in a new editor window.

<% if(contentString) { %>Now we can copy the content *<%= contentString; %>* with ctrl+c we want to insert into the file. <% } %>
<% if(lineNumber) { %>Inserting the content into a specific line number can be done by a left mouse click into the line *<%= lineNumber%>* and using the keyboard shortcut ctrl+v. Not every editor provides line numbers, if they are missing you have to count the numbers yourself.
<%}else if(placeholder) {%>To replace the content with a specific Placeholder you have to locate the placeholder in the file. The fastest way is to search through the file with ctrl+f and pasting the placeholder *<%= placeholder; %>* into the *Find next* or *Find* text field that will be opened. The placeholder will be marked in the text and you can replace him with the new content.
<% }else{ %>Now you can select the place you want to insert the content or just append it at the end of the file and paste the content with the shortcut ctrl+v. <% } %>

The final step is to save the file by selecting *Save* in the file context menu or by using the keyboard shortcut ctrl+s and a file has been changed.