== Create the file <%= fileName; %>

=== Creating <%= fileName; %> in an Editor

Create <%= fileName; %> in an Editor<% if(contentFile) { %> and insert some data from <%= contentFile; %> into it.

First, you want to open <%= contentFile; %> to get the data we want to put into <%= fileName; %>.
Go to the file context menu in the top left corner and choose *Open* or *Open File* or mostly the keyboard shortcut ctrl+o will also work. 
Based on your operating system a window with the file explorer opens. Navigate to <%= contentFile; %> and select it. Also, you can insert the path `<%= contentPath; %>` into the path bar, so you can jump into the right folder and select the file `<%= contentFile; %>`. 
Now confirm your inputs with the *Open* button in the bottom right corner.
A new editor window <%= fileName; %> will be opened, where you can select the whole text with the keyboard shortcut ctrl+a and copy the selected text with ctrl+c.<% } %>

Opening a new file can be done by going to the file context menu in the top left corner and select *New* or *New File* or mostly also the keyboard shortcut ctrl+n will also work.
The editor opens a new editor window for an untitled file that can be edited now.
<% if(contentPath) { %> 
Insert the previously copied text with a keyboard shortcut ctrl+v or with a right-click in the editor window and the paste function. <% } %>
The next step is to save the file by selecting *Save* or *Save as* in the file context menu or by using the keyboard shortcut ctrl+s.
A file explorer window opens.
You should check if you are currently in the right directory where you want to save <%= filePath; %><%= fileName;%>. 
Changing the directory can be done by inserting the path `<%= filePath; %>` in the path bar. If the directory does not exist, create the missing folders.
To save the file specify the name of the file. Paste `<%= fileName; %>` in the text field *File name:*. 
The last step is to save the file with the *Save* button in the bottom right corner and <%= fileName; %> has been created<% if(contentFile) { %> and filled with some data from <%= contentFile; %><%} %>.


