Create a file
============

Create a file from console
~~~~~~~~~~~~~~~~~~~~~~~~~~
First, you need to open a command prompt in your current Workspace. For Windows you can use Powershell or CMD and on Linux you can use the Terminal.

<% if(!directoryExists){ %>First we have to create the directory where the file gonne be created with the command `mkdir -p <%= directoryPath; %>` <% } %>

.Operating System
. Windows  <% if(contentPath) { %> + 
On Windows you can use many different commands for creating a file and writing content from another file into it, but we are just using the redirect function and printing the input from a file with command `more` and redirect it with `>` to our new file with `more <%= contentPath; %> > <%= filePath; %>`.
<% }else{ %> + 
To create a new file with no Value we just use the command fsutil file. More information about this function and the usage can be found https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil-file[here]. +
The command will be `fsutil file createnew <%= filePath; %> 4096`.
<% } %>

. Linux  <% if(contentPath) { %> + 
So we start using the function `cat` to create a file and also write the content from another file into it 
more information about usage you can get https://man7.org/linux/man-pages/man1/cat.1.htm[here]. +
The command will be `cat <%= contentPath; %> > <%= filePath; %>`.
<% }else{ %>  + 
So we start using the function `cat` to create a file more information about usage you can get https://man7.org/linux/man-pages/man1/cat.1.htm[here].
the command will be `cat <%= filePath; %>`.
<% } %>

