== Create the file <%= fileName; %>

==== Prerequisites
* Existing folder you want to load the file. (If the folder does not exist you can create it from terminal.)


.Operating system
. Linux and macOS + 
Execute the command `mkdir -p <%= filePath; %>`. The `-p` flag won't throw an error if the target folder already exists and allows the creation of parent directories.
. Windows + 
Execute the command to create a folder if not already existing `New-Item -ItemType Directory -Force -Path <%= filePath; %>`.


=== Create <%= fileName; %> from command prompt
We want to create a new file <% if(content){ %> and insert the following text into it.
<% if(fileType) { %>[source, <%= fileType; %>] <% } %>
----
<%= content; %>
----
<% } %>
First, you need to open a command prompt in your current workspace. For Windows, you can use PowerShell and on Linux, you can use the Terminal.

.Operating System
. Linux and macOS +
In the Terminal, we start using the command *cat* to create a new file<% if(content) { %> and write the content into it<% } %>. 
More information about the usage, you can find https://man7.org/linux/man-pages/man1/cat.1.htm[here].
To create a new empty <%= fileName; %> <% if(content) { %>and write the content from above into it, <% } %> you can execute the command 
`cat > <%= filePath; %><%= fileName;%>`. Now you can write some text into the Terminal that will be written into the file.  
<% if(content) {%>Copy the text from above and paste it into the Terminal to write the content to the file.
<%} %>Send an EOF with the keyboard shortcut ctrl+d to end the operation.

. Windows + 
In PowerShell, we use the cmdlet *New-Item* to create a new file<% if(content) { %> and to insert some content into the created file<% } %>.
More information about the *New-Item* cmdlet and the usage can be found https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-item?view=powershell-7.1[here]. 
To create a new empty <%= fileName; %> <% if(content){ %>and insert the content from above into it, <% } %>you can execute the following command, by pasting it into PowerShell.
+ 
----
New-Item  -Path "<%= filePath; %>" -Name <%= fileName; %> -ItemType "file" <% if(content) { %> -Value "<%= commandContent; %>"
----
<% } %> 



