Create a file
===============

Create a file
~~~~~~~~
First, you need to open a command prompt in your current Workspace. For Windows you can use Powershell or CMD and on Linux you can use the Terminal.

<% if(!directoryExists){ %>First we have to create the directory where the file gonne be created with the command `mkdir -p <%= directoryPath; %>` <% } %>

.OS
. Windows + 
<% if(contentPath) { %>
So we start using the command cat to create a file and also write the content from another file into it 
The command will be `more <%= contentPath; %> > <%= filePath; %>`.
<% }else{ %>
So we start using the command cat to create a file more information about usage you can get https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil-file[here].
the command will be `fsutil file createnew <%= filePath; %> 4096`.
<% } %>

. Linux + 
<% if(contentPath) { %>
So we start using the command cat to create a file and also write the content from another file into it 
more information about usage you can get https://man7.org/linux/man-pages/man1/cat.1.htm[here].
The command will be `cat <%= contentPath; %> > <%= filePath; %>`.
<% }else{ %>
So we start using the command cat to create a file more information about usage you can get https://man7.org/linux/man-pages/man1/cat.1.htm[here].
the command will be `cat <%= filePath; %>`.
<% } %>

