<% if(title){ %>== <%= title;%> 
=== Create folder
<%if(text){%><%- text; %> <%}%> 
<%}else if(title === undefined){%>=== Create folder
<%if(text){%><%- text; %> <%}%>
<%}else if(title === null){ %>== Create folder
<%if(text){%><%- text; %><%}%> <%}%>

=== Create folder
<%if(text){%><%- text; %><%}%><%}%>

==== Creating a new folder

A folder can be created either from within an IDE like VSCode or Eclipse by simply right clicking in the file explorer and creating a new folder. Another approach is to use the Terminal. 

.Operating system
. Linux or MacOS + 
You can use any file explorer like Finder or execute the command `mkdir -p <%= folderPath; %>`. The `-p` flag won't throw an error if the target folder already exists and allows the creation of parent directories.
. Windows + 
You can simply use the Windows Explorer to create the desired folder structure.Alternatively, use the batch command `if not exist <%= folderPath; %> mkdir <%= folderPath; %>` in your command prompt (CMD). For PowerShell users, refer to the command `New-Item -ItemType Directory -Force -Path <%= folderPath; %>`.

<%if(textAfter){%><%- textAfter; %><%}%>

