name: CI Windows
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        default: '--debug'

jobs:
  build:
    runs-on: 	windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
        
      - name: install Pandoc
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install pandoc

      - name: install Ruby
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install ruby

      - name: install AsciiDoctor
        run: gem install asciidoctor
        
      - name: install TS
        run: npm install -g typescript
      
      - name: npm install
        run: npm install

      - name: run checkout.ps1
        run: .\checkout.ps1

      - name: run buildRun.ps1 ${{ github.event.inputs.logLevel }}
        run: .\buildRun.ps1 ${{ github.event.inputs.logLevel }}
